#!/usr/bin/env python3
"""Write the CDS deployment.yaml for a local run.

    render_cds_config.py BASE OVERLAY TARGET DB NAME=VALUE ...

BASE is the configuration shipped in the repository, OVERLAY is
templates/cds-deployment.yaml. The overlay is filled in from the NAME=VALUE
pairs, merged onto the base and written to TARGET. DB (sqlite|postgres) picks
one of the overlay's datasource variants.

Placeholders are ${NAME}, or ${int:NAME} where the value has to be a number.
A placeholder with no value is an error, so a half-filled file never reaches
CDS.
"""
import re, sys, yaml

PLACEHOLDER = re.compile(r"\$\{(int:)?([A-Za-z_][A-Za-z_0-9]*)\}")
HEADER = "# Generated by scripts/local-setup/script.sh - edits are overwritten on the next run.\n"


def fill(node, values):
    """Replace every ${NAME} in a parsed overlay with its value."""
    if isinstance(node, dict):
        return {k: fill(v, values) for k, v in node.items()}
    if isinstance(node, list):
        return [fill(v, values) for v in node]
    if not isinstance(node, str):
        return node

    whole = PLACEHOLDER.fullmatch(node)
    if whole:
        typed, name = whole.group(1), whole.group(2)
        if name not in values:
            sys.exit("render_cds_config.py: no value for ${%s}" % name)
        return int(values[name]) if typed else values[name]

    def one(match):
        if match.group(2) not in values:
            sys.exit("render_cds_config.py: no value for ${%s}" % match.group(2))
        return values[match.group(2)]

    return PLACEHOLDER.sub(one, node)


def merge(base, overlay):
    """Deep-merge dicts; anything else in the overlay replaces the base value."""
    if not (isinstance(base, dict) and isinstance(overlay, dict)):
        return overlay
    out = dict(base)
    for key, value in overlay.items():
        out[key] = merge(out.get(key), value) if key in out else value
    return out


def scrub(node):
    """Blank out ${...} left in the base config.

    Those are environment-variable references CDS expands at load time; left
    alone they would quietly become empty strings anyway, so make it explicit.
    """
    if isinstance(node, dict):
        return {k: scrub(v) for k, v in node.items()}
    if isinstance(node, list):
        return [scrub(v) for v in node]
    if isinstance(node, str) and "${" in node:
        return ""
    return node


def main(argv):
    if len(argv) < 5:
        sys.exit(__doc__)
    base_path, overlay_path, target, db = argv[1:5]
    values = {}
    for arg in argv[5:]:
        if "=" not in arg:
            sys.exit("render_cds_config.py: expected NAME=VALUE, got %r" % arg)
        name, value = arg.split("=", 1)
        values[name] = value

    cfg = yaml.safe_load(open(base_path))
    overlay = fill(yaml.safe_load(open(overlay_path)), values)

    variants = overlay.pop("datasource_variants", {})
    if db not in variants:
        sys.exit("render_cds_config.py: no datasource variant for %r" % db)

    cfg = merge(cfg, overlay)
    # Replaced rather than merged: an SQLite run must not keep the shipped
    # PostgreSQL connection keys.
    cfg["datasource"] = variants[db]
    cfg = scrub(cfg)

    with open(target, "w") as fh:
        fh.write(HEADER)
        yaml.safe_dump(cfg, fh, default_flow_style=False, sort_keys=False, width=120)

    required = cfg.get("auth_server", {}).get("required_scopes") or {}
    flat = sorted({s for v in required.values() for s in v})
    print("    %d operations mapped to %d scopes" % (len(required), len(flat)))
    unexpected = [s for s in flat if not s.startswith("internal_cds_")]
    if unexpected:
        print("    ! required_scopes contains unregistered scope(s): %s" % ", ".join(unexpected))


if __name__ == "__main__":
    main(sys.argv)
